project:
  type: book
  execute-dir: project
  output-dir: docs
  
execute: 
  freeze: auto

format:
  html:
    theme:
      - lumen
    grid: 
      sidebar-width: 350px
    fontsize: "100%"
    template-partials:
      - toc.html
    toc-title: "On this page"
  # pdf:
  #   documentclass: scrreprt
  #   mainfont: "Open Sans"
  #   fig-pos: "H"
  #   include-in-header:
  #     text: |
  #       \usepackage{float}
  #       \raggedbottom

book:
  title: "SOURCEBOOK"
  repo-url: https://github.com/housingforwardva/sourcebook-2.0
  author: 
    name: "HousingForward Virginia"
    url: https://www.housingforwardva.org
  # downloads: pdf 
  date: today
  chapters:
    - index.qmd 
    - part: "DEMOGRAPHICS"
      chapters:
        - population.qmd # Total Population
    #     - race.qmd # Race and Ethnicity
    #     - age.qmd # Age
    #     - hhtype.qmd # Household Type
    #     - hhsize.qmd # Household Size
    # - part: "ECONOMICS"
    #   chapters:
    #     - hhincome.qmd # Household Income
    #     - poverty.qmd # Poverty
    #     - employment.qmd # Employment
    # - part: "INVENTORY"
    #   chapters: 
    #     - htype.qmd # Housing Type
    #     - hage.qmd # Housing Age
    #     - hchar.qmd # Housing Characteristics
    #     - overcrowd.qmd # Overcrowding
    # - part: "HOMEOWNERSHIP"
    #   chapters:
    #     - horate.qmd # Homeownership Rate
    #     - sales.qmd # Home Sales
    #     - hpi.qmd # House Price Index
    #     - mortgages.qmd # Mortgages
    # - part: "RENTAL"
    #   chapters: 
    #     - rent.qmd # Rent
    #     - rvacancy.qmd # Rental Vacancy
    #     - assisted.qmd # Assisted Rentals
    # - part: "AFFORDABILITY"
    #   chapters:
    #     - cb.qmd # Cost Burden
    #     - gap.qmd # Rental Housing Gap
    #     - ami.qmd # HUD AMI Limits
    # - part: "INSTABILITY"
    #   chapters:
    #     - pit.qmd # Homelessness

knitr:
  opts_chunk: 
    echo: false
    warning: false
    message: false
    
filters: 
  - shinylive